-- Phase 1 draft schema for PostgreSQL. Review business decisions before applying.
-- UUIDs are generated by the application. All timestamps are stored in UTC.

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE app_users (
  id uuid PRIMARY KEY,
  email text NOT NULL UNIQUE,
  display_name text NOT NULL,
  role text NOT NULL CHECK (role IN ('ADMIN', 'LEADER', 'SALES')),
  identity_subject text UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX app_users_email_lower_unique ON app_users (lower(email));

CREATE TABLE people (
  id uuid PRIMARY KEY,
  full_name text NOT NULL,
  date_of_birth date,
  gender text,
  government_id_ciphertext bytea,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE person_phones (
  id uuid PRIMARY KEY,
  person_id uuid NOT NULL REFERENCES people(id),
  phone_normalized text NOT NULL,
  phone_original text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (person_id, phone_normalized)
);
CREATE INDEX person_phones_phone_idx ON person_phones (phone_normalized);

CREATE TABLE programs (
  id uuid PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE intakes (
  id uuid PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  starts_on date,
  ends_on date
);

CREATE TABLE lead_sources (
  id uuid PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  channel text NOT NULL
);

CREATE TABLE ctv (
  id uuid PRIMARY KEY,
  display_name text NOT NULL,
  phone_normalized text,
  category text,
  current_owner_sales_id uuid REFERENCES app_users(id),
  is_active boolean NOT NULL DEFAULT true,
  joined_on date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ctv_sales_assignments (
  id uuid PRIMARY KEY,
  ctv_id uuid NOT NULL REFERENCES ctv(id),
  sales_id uuid NOT NULL REFERENCES app_users(id),
  effective_from timestamptz NOT NULL,
  effective_to timestamptz,
  created_by uuid NOT NULL REFERENCES app_users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_to IS NULL OR effective_to > effective_from),
  EXCLUDE USING gist (
    ctv_id WITH =,
    tstzrange(effective_from, effective_to, '[)') WITH &&
  )
);
CREATE INDEX ctv_sales_assignments_lookup_idx
  ON ctv_sales_assignments (ctv_id, effective_from DESC);

CREATE TABLE applications (
  id uuid PRIMARY KEY,
  person_id uuid NOT NULL REFERENCES people(id),
  program_id uuid REFERENCES programs(id),
  intake_id uuid REFERENCES intakes(id),
  source_id uuid REFERENCES lead_sources(id),
  sales_owner_id uuid NOT NULL REFERENCES app_users(id),
  referrer_ctv_id uuid REFERENCES ctv(id),
  stage text NOT NULL CHECK (stage IN (
    'NEW', 'CONTACTED', 'CONSULTING', 'WAITING_DOCUMENTS',
    'WAITING_PAYMENT', 'NE', 'ENROLLED', 'LOST'
  )),
  lost_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((stage = 'LOST') = (lost_reason IS NOT NULL))
);
CREATE INDEX applications_sales_stage_idx
  ON applications (sales_owner_id, stage, created_at DESC);
CREATE INDEX applications_ctv_idx ON applications (referrer_ctv_id, created_at DESC);
CREATE INDEX applications_intake_program_idx ON applications (intake_id, program_id);

CREATE TABLE application_stage_events (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  old_stage text,
  new_stage text NOT NULL,
  reason text,
  changed_by uuid NOT NULL REFERENCES app_users(id),
  changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX application_stage_events_time_idx
  ON application_stage_events (application_id, changed_at DESC);

CREATE TABLE application_owner_events (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  old_sales_id uuid REFERENCES app_users(id),
  new_sales_id uuid NOT NULL REFERENCES app_users(id),
  reason text,
  changed_by uuid NOT NULL REFERENCES app_users(id),
  changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX application_owner_events_time_idx
  ON application_owner_events (application_id, changed_at DESC);

CREATE TABLE activities (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  actor_user_id uuid NOT NULL REFERENCES app_users(id),
  kind text NOT NULL CHECK (kind IN ('CALL', 'MESSAGE', 'MEETING', 'NOTE')),
  occurred_at timestamptz NOT NULL,
  outcome text,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX activities_application_time_idx
  ON activities (application_id, occurred_at DESC);

CREATE TABLE follow_up_tasks (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  assignee_id uuid NOT NULL REFERENCES app_users(id),
  due_at timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('OPEN', 'DONE', 'CANCELLED')),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX follow_up_tasks_due_idx ON follow_up_tasks (assignee_id, status, due_at);

CREATE TABLE payment_transactions (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  kind text NOT NULL CHECK (kind IN (
    'TUITION_RECEIPT', 'TUITION_REFUND', 'APPLICATION_FEE', 'DEPOSIT'
  )),
  amount_vnd numeric(16, 0) NOT NULL CHECK (amount_vnd > 0),
  bank_at timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED')),
  original_receipt_id uuid REFERENCES payment_transactions(id),
  evidence_storage_key text,
  recorded_by uuid NOT NULL REFERENCES app_users(id),
  confirmed_by uuid REFERENCES app_users(id),
  confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'CONFIRMED') = (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)),
  CHECK (kind <> 'TUITION_REFUND' OR original_receipt_id IS NOT NULL)
);
CREATE INDEX payment_transactions_application_idx
  ON payment_transactions (application_id, bank_at);

-- Insert one signed NE event when confirmed tuition crosses zero to positive,
-- when full refund reaches zero, or when later tuition makes it positive again.
-- event_at is the bank receipt/refund time, not the confirmation time.
CREATE TABLE ne_events (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  payment_transaction_id uuid NOT NULL UNIQUE REFERENCES payment_transactions(id),
  kind text NOT NULL CHECK (kind IN ('RECOGNIZED', 'REVERSED', 'REINSTATED')),
  delta smallint NOT NULL CHECK (delta IN (-1, 1)),
  event_at timestamptz NOT NULL,
  credited_sales_id uuid NOT NULL REFERENCES app_users(id),
  referrer_ctv_id uuid REFERENCES ctv(id),
  ctv_manager_at_ne_id uuid REFERENCES app_users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((kind = 'REVERSED' AND delta = -1) OR
         (kind IN ('RECOGNIZED', 'REINSTATED') AND delta = 1))
);
CREATE INDEX ne_events_period_idx ON ne_events (event_at, credited_sales_id);
CREATE INDEX ne_events_ctv_scope_idx ON ne_events (ctv_manager_at_ne_id, event_at);

CREATE TABLE document_items (
  id uuid PRIMARY KEY,
  application_id uuid NOT NULL REFERENCES applications(id),
  document_type text NOT NULL,
  status text NOT NULL CHECK (status IN ('MISSING', 'RECEIVED', 'VERIFIED', 'REJECTED')),
  storage_key text,
  reviewed_by uuid REFERENCES app_users(id),
  reviewed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (application_id, document_type)
);

CREATE TABLE import_batches (
  id uuid PRIMARY KEY,
  source_filename text NOT NULL,
  source_sha256 text NOT NULL,
  status text NOT NULL CHECK (status IN ('PREVIEW', 'COMMITTED', 'FAILED')),
  created_by uuid NOT NULL REFERENCES app_users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  committed_at timestamptz
);

CREATE TABLE import_rows (
  id uuid PRIMARY KEY,
  import_batch_id uuid NOT NULL REFERENCES import_batches(id),
  source_sheet text NOT NULL,
  source_row integer NOT NULL CHECK (source_row > 0),
  status text NOT NULL CHECK (status IN ('VALID', 'REVIEW', 'IMPORTED', 'SKIPPED', 'ERROR')),
  application_id uuid REFERENCES applications(id),
  issue_codes text[] NOT NULL DEFAULT '{}',
  UNIQUE (import_batch_id, source_sheet, source_row)
);

CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  actor_user_id uuid REFERENCES app_users(id),
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  action text NOT NULL,
  before_data jsonb,
  after_data jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_events_entity_time_idx
  ON audit_events (entity_type, entity_id, occurred_at DESC);
